POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Leo",
  "email": "leo.dumont@outlook.com"
}

###

GET http://localhost:3333/invites/teste123

###

GET http://localhost:3333/subscribers/teste123/ranking/clicks