POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Indicated user",
  "email": "indicated@email.com",
  "referrer": "b8b9f1a1-a062-4a48-a25a-116b92c00990"
}

###

GET http://localhost:3333/invites/teste123

###

GET http://localhost:3333/invites/b8b9f1a1-a062-4a48-a25a-116b92c00990

###

GET http://localhost:3333/subscribers/teste123/ranking/clicks

###

GET http://localhost:3333/subscribers/b8b9f1a1-a062-4a48-a25a-116b92c00990/ranking/clicks