services:
  service-pg:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=connect
    volumes:
      - pg-data:/bitnami/postgresql
  service-redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis
    
volumes:
  pg-data:
  redis-data: